# Generated by Django 4.1.2 on 2023-09-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_info_provided',
            field=models.BooleanField(default=False),
        ),
    ]
