# Generated by Django 4.1.2 on 2023-09-03 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_payment_info_provided'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='payment_info_provided',
        ),
    ]
