# Generated by Django 4.1.2 on 2023-09-03 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='payment_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_address', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('btc_address', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('payoneer_address', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('provided_info', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Testimonial',
            },
        ),
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='case_studies',
            options={'verbose_name_plural': 'Case Studies'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Service'},
        ),
        migrations.AlterModelOptions(
            name='site_info',
            options={'verbose_name_plural': 'Site Info'},
        ),
        migrations.RenameField(
            model_name='services',
            old_name='url',
            new_name='url_to_go',
        ),
        migrations.AlterField(
            model_name='about_us',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='case_studies',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
