# Generated by Django 4.1.2 on 2023-09-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact_us_payment_method_testimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_method',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
