# Generated by Django 4.1.2 on 2023-09-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_payment_method_provided_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='url_to_go',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
