# Generated by Django 4.1.2 on 2023-09-13 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_services_url_to_go'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_method',
            name='amount',
        ),
    ]
