# Generated by Django 4.1.2 on 2023-09-14 01:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_remove_payment_method_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment_method',
            new_name='payment_request',
        ),
    ]
